services:
  - type: web
    name: messenger-hf-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: HF_API_KEY
        sync: false
